drop table users;
DROP SEQUENCE myBatisSampleSeq RESTRICT;

CREATE SEQUENCE myBatisSampleSeq AS INT START WITH 0;

create table users(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	fullName VARCHAR(50), 
	email VARCHAR(50), 
	address VARCHAR(50),
	mobile VARCHAR(50)
);